version: '3.8'

services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "5000:5000"
    env_file:
      - ./services/auth-service/.env
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    restart: always