version: '3.8'

services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./services/auth-service/.env
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules
    command: ["npx", "nodemon", "server.js"]

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: skillsly_db
      MYSQL_USER: benjaminsmerd
      MYSQL_PASSWORD: Summerland!5
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: